#
# more information can be found here http://sonata-project.org/bundles/admin
#
parameters:    
    # Sonata Admin Options
    sonata_admin.title:             Emailing System
    sonata_admin.logo_title:        /img/admin/visa.png
    
sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.role

    title:      %sonata_admin.title%
    title_logo: %sonata_admin.logo_title%
    templates:
        # default global templates
#        layout:  SonataAdminBundle::standard_layout.html.twig
        layout:  AdminThemeBundle::layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default value if done set, actions templates, should extends a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
#        list:    AdminThemeBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
#            - { position: right, type: sonata.admin_doctrine_orm.block.audit}
            - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Добро пожаловать!</h2><br/><p>Панель управления предоставляет возможность:</p><ul><li>управлять рассылками</li><li>управлять списком получателей</li><li>управлять группами получателей</li><li>просматривать статистику</li></ul>"} }
#            - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}

sonata_doctrine_orm_admin:
    entity_manager: ~
    templates:
        form:
            - AdminThemeBundle:Form:form_admin_fields.html.twig
        filter:
            - SonataDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig