ApplicationSonataUserBundle_user_routes:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing.yml"
    prefix:   /

HelloBundle:
    resource: "@HelloBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

sonata_user_impersonating:
    pattern:  /admin/dashboard
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

sonata_media_gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

sonata_media_media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_media_pixlr:
    resource: '@SonataMediaBundle/Resources/config/routing/pixlr.xml'
    prefix: /admin/media

_imagine:
    resource: .
    type:     imagine

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

ok_bundle:
    resource: '@OKBundle/Resources/config/routing.yml'
    prefix: /ok
vk_bundle:
    resource: '@VKBundle/Resources/config/routing.yml'
    prefix: /vk

fb_bundle:
    resource: '@AiloveFacebookBundle/Resources/config/routing.yml'
    prefix: /fb
