# 
# more information can be found here http://sonata-project.org/bundles/user
#
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
    registration:
        confirmation:
            from_email:
                address: reallove.videomore@gmail.com
                sender_name: Настоящая любовь
            enabled: true
            template: ApplicationSonataUserBundle:Registration:email.txt.twig
        form:
            type: firstlove_registration_form_type
            handler: firstlove.registration_form_handler
            validation_groups: [FirstloveRegistration]
#    resetting:
#        token_ttl: 86400
#        email:
#            from_email:
#                address: support@sochi2014-sberbank.ru
#                sender_name: Sochi2014 Sberbank portal
#            template:   FOSUserBundle:Resetting:email.txt.twig
#        form:
#            type:               fos_user_resetting
#            handler:            fos_user.resetting.form.handler.default
#            name:               fos_user_resetting_form
#            validation_groups:  [ResetPassword]
# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~
